<a href="https://colab.research.google.com/github/Jaikirao/Differencing-Attack-on-Row-10/blob/master/differencing_privacy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

# the number of entries in our database
num_entries = 20

db = torch.rand(num_entries) > 0.5
db

tensor([0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
       dtype=torch.uint8)

In [0]:
def get_parallel_db(db , remove_index):
  return torch.cat((db[0:remove_index],
                    db[remove_index+1:]))

In [0]:
get_parallel_db(db,2)

tensor([0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
       dtype=torch.uint8)

In [0]:
def get_parallel_dbs(db):
  parallel_dbs=list()
  for i in range(len(db)):
    pdb=get_parallel_db(db,i)
    parallel_dbs.append(pdb)
    
  return parallel_dbs


In [0]:
get_parallel_dbs(db)

[tensor([1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,

In [0]:
def create_db_and_parallel(num_enteries):
  db=torch.rand(num_enteries)>0.5
  pdbs= get_parallel_dbs(db)
  
  return db,pdbs

In [0]:
db,pdbs =create_db_and_parallel(10)

In [0]:
db

tensor([1, 1, 0, 0, 1, 0, 0, 1, 1, 0], dtype=torch.uint8)

In [0]:
pdbs

[tensor([1, 0, 0, 1, 0, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 1, 0, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 1, 0, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 1, 0, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 0, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 1, 0, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 1, 0, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 1, 0, 0, 1, 0, 0, 1, 1], dtype=torch.uint8)]

In [0]:
db, pdbs = create_db_and_parallel(5000)

In [0]:
def query(db):
    return db.sum()

In [0]:
full_db_result = query(db)

In [0]:
sensitivity = 0
for pdb in pdbs:
    pdb_result = query(pdb)
    
    db_distance = torch.abs(pdb_result - full_db_result)
    
    if(db_distance > sensitivity):
        sensitivity = db_distance

In [0]:
sensitivity

tensor(1)

In [0]:
db, pdbs = create_db_and_parallel(5000)

In [0]:
full_db_result = query(db)

In [0]:
def sensitivity(query,n_enteries=1000):
  db, pdbs = create_db_and_parallel(n_enteries)
  full_db_result = query(db)
  max_distance = 0
  for pdb in pdbs:
    
    pdb_result = query(pdb)
    
    db_distance = torch.abs(pdb_result - full_db_result)
    
    if(db_distance > max_distance):
        max_distance = db_distance
  return max_distance

In [0]:
def query(db):
    return db.float().mean()

In [0]:
sensitivity(query)

tensor(0.0005)

In [0]:
db, pdbs = create_db_and_parallel(10)
db

tensor([1, 0, 0, 0, 1, 1, 0, 1, 1, 0], dtype=torch.uint8)

In [0]:
pdbs

[tensor([0, 0, 0, 1, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 1, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 1, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 1, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 0, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 1, 1, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 1, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 1, 0, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 0, 0, 1, 1, 0, 1, 1], dtype=torch.uint8)]

In [0]:
def query(db, threshold=5):
  return (db.sum()>threshold).float()

In [0]:
db, pdbs = create_db_and_parallel(10)
db.sum()

tensor(2)

In [0]:
db.sum()>5

tensor(0, dtype=torch.uint8)

In [0]:
query(db)

tensor(0.)

In [0]:
for i in range(10):
  sen_f=sensitivity(query,n_enteries=10)
  print(sen_f)

0
tensor(1.)
tensor(1.)
0
0
tensor(1.)
0
0
0
0


In [0]:
db, _ =create_db_and_parallel(100)
db


tensor([1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 0], dtype=torch.uint8)

In [0]:
pdb= get_parallel_db(db,remove_index=10)

In [0]:
db[10]

tensor(1, dtype=torch.uint8)

In [0]:
sum(db)

tensor(54, dtype=torch.uint8)

In [0]:
#differencing privacy using sum

sum(db)-sum(pdb)


tensor(255, dtype=torch.uint8)

In [0]:
#differencing privacy using mean function

(sum(db).float()/len(db))-(sum(pdb).float()/len(pdb))

tensor(0.0046)

In [0]:
#differencing privacy using threshold

(sum(db)>53)-(sum(pdb)>53)

tensor(1, dtype=torch.uint8)

In [0]:
#differencing privacy using threshold
#if we take greater than hte sum(db) the output will be 0

(sum(db)>55)-(sum(pdb)>55)

tensor(0, dtype=torch.uint8)